apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-windows
  namespace: windows
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: hostpath

