apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: centos6-server-small
  annotations:
    template.kubevirt.io/deprecated: "true"
    openshift.io/display-name: "CentOS 6 VM"
    description: >-
      Template for CentOS 6 VM or newer.
      A PVC with the CentOS disk image must be available.
    tags: "hidden,kubevirt,virtualmachine,linux,centos"
    iconClass: "icon-centos"
    openshift.io/provider-display-name: "KubeVirt"
    openshift.io/documentation-url: "https://github.com/kubevirt/common-templates"
    openshift.io/support-url: "https://github.com/kubevirt/common-templates/issues"
    template.openshift.io/bindable: "false"
    template.kubevirt.io/version: v1alpha1
    defaults.template.kubevirt.io/disk: rootdisk
    template.kubevirt.io/editable: |
      /objects[0].spec.template.spec.domain.cpu.sockets
      /objects[0].spec.template.spec.domain.cpu.cores
      /objects[0].spec.template.spec.domain.cpu.threads
      /objects[0].spec.template.spec.domain.memory.guest
      /objects[0].spec.template.spec.domain.devices.disks
      /objects[0].spec.template.spec.volumes
      /objects[0].spec.template.spec.networks
    name.os.template.kubevirt.io/centos6.0: CentOS 6.0 or higher
    name.os.template.kubevirt.io/centos6.1: CentOS 6.0 or higher
    name.os.template.kubevirt.io/centos6.10: CentOS 6.0 or higher
    name.os.template.kubevirt.io/centos6.2: CentOS 6.0 or higher
    name.os.template.kubevirt.io/centos6.3: CentOS 6.0 or higher
    name.os.template.kubevirt.io/centos6.4: CentOS 6.0 or higher
    name.os.template.kubevirt.io/centos6.5: CentOS 6.0 or higher
    name.os.template.kubevirt.io/centos6.6: CentOS 6.0 or higher
    name.os.template.kubevirt.io/centos6.7: CentOS 6.0 or higher
    name.os.template.kubevirt.io/centos6.8: CentOS 6.0 or higher
    name.os.template.kubevirt.io/centos6.9: CentOS 6.0 or higher
  labels:
    os.template.kubevirt.io/centos6.0: "true"
    os.template.kubevirt.io/centos6.1: "true"
    os.template.kubevirt.io/centos6.10: "true"
    os.template.kubevirt.io/centos6.2: "true"
    os.template.kubevirt.io/centos6.3: "true"
    os.template.kubevirt.io/centos6.4: "true"
    os.template.kubevirt.io/centos6.5: "true"
    os.template.kubevirt.io/centos6.6: "true"
    os.template.kubevirt.io/centos6.7: "true"
    os.template.kubevirt.io/centos6.8: "true"
    os.template.kubevirt.io/centos6.9: "true"
    workload.template.kubevirt.io/server: "true"
    flavor.template.kubevirt.io/small: "true"
    template.kubevirt.io/type: "base"
    template.kubevirt.io/version: "devel"
    template.kubevirt.io/default-os-variant: "true"
objects:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    name: ${NAME}
    labels:
      vm.kubevirt.io/template: centos6-server-small
      vm.kubevirt.io/template.version: "devel"
      vm.kubevirt.io/template.revision: "1"
      app: ${NAME}
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.memory.guest",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 536870912
          }
        ]
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: ${NAME}
      spec:
        storage:
          resources:
            requests:
              storage: 30Gi
        sourceRef:
          kind: DataSource
          name: ${DATA_SOURCE_NAME}
          namespace: ${DATA_SOURCE_NAMESPACE}
    runStrategy: Halted
    template:
      metadata:
        annotations:
          vm.kubevirt.io/os: "centos6"
          vm.kubevirt.io/workload: "server"
          vm.kubevirt.io/flavor: "small"
        labels:
          kubevirt.io/domain: ${NAME}
          kubevirt.io/size: small
      spec:
        architecture: amd64
        domain:
          cpu:
            sockets: 1
            cores: 1
            threads: 1
          memory:
            guest: 2Gi
          devices:
            useVirtioTransitional: true
            rng: {}
            disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
            - masquerade: {}
              name: default
              model: virtio
        terminationGracePeriodSeconds: 180
        networks:
        - name: default
          pod: {}
        volumes:
        - dataVolume:
            name: ${NAME}
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: centos
              password: ${CLOUD_USER_PASSWORD}
              chpasswd: { expire: False }
          name: cloudinitdisk
parameters:
- description: VM name
  from: 'centos6-[a-z0-9]{16}'
  generate: expression
  name: NAME
- name: DATA_SOURCE_NAME
  description: Name of the DataSource to clone
  value: 'centos6'
- name: DATA_SOURCE_NAMESPACE
  description: Namespace of the DataSource
  value: kubevirt-os-images
- description: Randomized password for the cloud-init user centos
  from: '[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}'
  generate: expression
  name: CLOUD_USER_PASSWORD
