apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: linux
  namespace: linux
  labels:
    vm.kubevirt.io/template: linux-desktop-large
    vm.kubevirt.io/template.version: "devel"
    vm.kubevirt.io/template.revision: "1"
    app: linux
  annotations:
    vm.kubevirt.io/validations: |
      [
        {
          "name": "minimal-required-memory",
          "path": "jsonpath::.spec.domain.memory.guest",
          "rule": "integer",
          "message": "This VM requires more memory.",
          "min": 2147483648
        }
      ]
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/os: "linux"
        vm.kubevirt.io/workload: "desktop"
        vm.kubevirt.io/flavor: "large"
      labels:
        kubevirt.io/domain: linux
        kubevirt.io/size: large
    spec:
      architecture: amd64
      domain:
        cpu:
          sockets: 2
          cores: 1
          threads: 1
        memory:
          guest: 8Gi
        devices:
          rng: {}
          networkInterfaceMultiqueue: true
          inputs:
            - type: tablet
              bus: virtio
              name: tablet
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          interfaces:
          - masquerade: {}
            name: default
            model: virtio
      terminationGracePeriodSeconds: 30
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        persistentVolumeClaim:
          claimName: archlinux-iso
