apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu
        kubevirt.io/size: large
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: sata
            name: rootdisk
          interfaces:
          - masquerade: {}
            name: default
            model: virtio
        resources:
          requests:
            memory: 4Gi
      terminationGracePeriodSeconds: 30
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        persistentVolumeClaim:
          claimName: ubuntu-iso
