apiVersion: v1
kind: PersistentVolume
metadata:
  name: linux-data
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/hostImages/linux-data"
