apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linux-data
  namespace: linux
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: hostpath

