---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`prometheus.jedric.local`)
    kind: Rule
    services:
    - name: prometheus-operated
      port: 9090
