---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: device-dev-sda
spec:
  capacity:
    storage: 447Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /dev/sda
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
           - key: kubernetes.io/hostname
             operator: In
             values:
               - jedric
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-disk
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: local-storage
  resources:
    requests:
      storage: 447Gi
