FROM archlinux:base

RUN pacman -Sy

RUN pacman -S --noconfirm i3-wm dmenu vim ranger nemo firefox i3status xss-lock
RUN pacman -S --noconfirm networkmanager network-manager-applet
RUN pacman -S --noconfirm alacritty

CMD i3