---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`grafana.jedric.local`)
    kind: Rule
    services:
    - name: prometheus-operator-grafana
      port: 80
