apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-vmi
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: fedora-vmi
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          autoattachGraphicsDevice: false
          hostDevices:
          - deviceName: nvidia.com/RTX3060_GPU
            name: gpu
          - deviceName: nvidia.com/RTX3060_AUDIO
            name: audio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 2Gi
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: kubevirt/fedora-cloud-container-disk-demo:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
