apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: archlinux
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: archlinux
        kubevirt.io/size: large
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 2
          threads: 2
        firmware:
          bootloader:
            efi:
              persistent: true
              secureBoot: false
        devices:
          clientPassthrough: {}
          autoattachGraphicsDevice: false
          hostDevices:
          - deviceName: nvidia.com/RTX3060_GPU
            name: gpu
          - deviceName: nvidia.com/RTX3060_AUDIO
            name: audio
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          interfaces:
          - masquerade: {}
            name: default
            model: virtio
        resources:
          requests:
            memory: 12Gi
      terminationGracePeriodSeconds: 30
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        persistentVolumeClaim:
          claimName: archlinux-data
