---
apiVersion: v1
kind: Service
metadata:
  name: adguard
  namespace: adguard
  labels:
    app: adguard
spec:
  type: ClusterIP
  selector:
    app: adguard
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: http-setup
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  - protocol: UDP
    port: 53
    targetPort: 53
    name: udp-dns
  - protocol: TCP
    port: 53
    targetPort: 53
    name: tcp-dns
